version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - phpmyadmin
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bid_lotto
      - MYSQL_USER=bid_lotto
      - MYSQL_PASSWORD=bid_lotto
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=bid_lotto
      - PMA_PASSWORD=bid_lotto
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge